/**
 * DO NOT EDIT THIS FILE!
 *
 * This module is automatically generated by kanso when the app is pushed to
 * the database and exports the settings stored in kanso.json in the project's
 * directory.
 *
 * For the code that generates this file, see: lib/settings.js
 */

/**
 * The settings module is automatically generated by Kanso and contains the
 * settings defined in your app's kanso.json configuration file.
 *
 * @module
 */
