/**
 * DO NOT EDIT THIS FILE!
 *
 * This module is automatically generated by kanso when the app is pushed to
 * the database.
 *
 * This is to work around the fact that dust templates store state
 * on the module itself but couchdb doesn't yet provide a module cache,
 * meaning state does not persist between each require(). The workaround
 * involves writing all templates directly into the module, so they are added on
 * each require.
 *
 * TODO: When a module cache is implemented in CouchDB, stop this module from
 * being auto-generated, see: https://issues.apache.org/jira/browse/COUCHDB-890
 *
 * For the code that generates this file, see: lib/templates.js
 */
