module.exports = {
    help: require('./help'),
    push: require('./push'),
    upload: require('./upload'),
    show: require('./show'),
    createdb: require('./createdb'),
    deletedb: require('./deletedb'),
    listdb: require('./listdb'),
    replicate: require('./replicate'),
    transform: require('./transform'),
    uuids: require('./uuids'),
    pack: require('./pack'),
    publish: require('./publish'),
    unpublish: require('./unpublish'),
    install: require('./install'),
    update: require('./update'),
    clean: require('./clean'),
    'clear-cache': require('./clear-cache'),
    ls: require('./ls')
};
